import { ethers } from 'ethers';
import { createSolanaWallet } from './solana.js';

/**
 * A "wallet" in this bot is a pair of keypairs under one name: an EVM
 * keypair (same address works on Ethereum/Base/Arbitrum/BSC/Robinhood Chain
 * — that's just how EVM addresses work) and a Solana keypair (different
 * curve, needs its own key). This is what lets one wallet trade USDC on
 * every supported chain without the user ever thinking about bridging.
 *
 * evmPrivateKey / solPrivateKey are the DECRYPTED values in memory — storage.js
 * encrypts each independently before writing to disk.
 *
 * Wallets are always generated by the bot, never imported — mirrors the
 * embedded-wallet model (create on signup, export anytime as a backup, no
 * "paste your key in" flow) rather than accepting an existing private key.
 * Users can still get their keys out at any time via 🔑 Export Key.
 */
export function createWallet(name) {
  const evm = ethers.Wallet.createRandom();
  const sol = createSolanaWallet();
  return {
    name,
    evmAddress: evm.address,
    evmPrivateKey: evm.privateKey,
    solAddress: sol.address,
    solPrivateKey: sol.privateKey,
  };
}

export function shortAddr(addr) {
  return `${addr.slice(0, 6)}...${addr.slice(-4)}`;
}
